name: Pushing from github to gitlab
on:
  push:
    branches:
      - main
jobs:
  copy-files:
    runs-on: ubuntu-latest
    environment: gitlabAss1
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Copy files to GitLab workshop
      env:
        TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        echo "pushing files to GitLab"
        git fetch --unshallow "https://github.com/yasinhessnawi1/Assignment1/"
        git config user.name "yasinmh"
        git config user.email "yasinmh@ntnu.no"
        git remote add gitlab "https://git.gvk.idi.ntnu.no/course/prog2005/prog2005-2024-workspace/yasinmh/assignment_cloud_technology"
        git remote set-url gitlab "https://oauth2=$TOKEN@git.gvk.idi.ntnu.no/course/prog2005/prog2005-2024-workspace/yasinmh/assignment_cloud_technology"
        git push -u gitlab --all
        git push -u gitlab --tags
