name: Pushing from github to gitlab
on:
  push:
    branches:
      - main
jobs:
  copy-files:
    runs-on: ubuntu-latest
    environment: gitlabAss1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Copy files to GitLab workshop
        env:
          TOKEN: ${{secrets.GITLAB_TOKEN}}
        run: |
          echo "pushing files to GitLab"
          git config user.name "yasinmh"
          git config user.email "yasinmh@ntnu.no"
          git remote add gitlab git@git.gvk.idi.ntnu.no:course/prog2005/prog2005-2024-workspace/yasinmh/assignment1.git
          git push -u gitlab --all
          git push -u gitlab --tags
